### ISSUE TITLE
Error when logging in at Home page 

### ISSUE THREAD

**Issue by bettafish15** [Epi-Info/Epi-Info-Cloud-Data-Capture#3]
After signing in, there was this unspecified error which I have not figured it out. Maybe you can help me out with it? I would very much appreciate it. Let me know if you need more information in order to identify and fix this issue. Thank you.
<img width="960" alt="Untitled" src="https://user-images.githubusercontent.com/40290448/76166157-00ceec80-618f-11ea-8983-2fa69c95c153.png">
P/s: This is my error stack trace:

Stack Trace: at  Epi.Web.MVC.Repositories.IntegratedSurveyAnswerRepository.GetOrganizationsByUserId(OrganizationRequest OrgReq) in C:\EWE\Epi.Web\Repositories\IntegratedSurveyAnswerRepository.cs:line 550 at Epi.Web.MVC.Facade.SurveyFacade.GetOrganizationsByUserId(OrganizationRequest OrgRequest) in C:\EWE\Epi.Web\Facade\SurveyFacade.cs:line 408 at Epi.Web.MVC.Controllers.HomeController.GetFormModel(String surveyid, Int32 UserId, Guid UserId1, Int32& OrgnizationId, FormModel& FormModel) in C:\EWE\Epi.Web\Controllers\HomeController.cs:line 117 at Epi.Web.MVC.Controllers.HomeController.Index(String surveyid, Int32 orgid) in C:\EWE\Epi.Web\Controllers\HomeController.cs:line 66 Message: The creator of this fault did not specify a Reason.

**Comment by mlamtahri** [comment]
In the documentation, There are few steps on how to add an encrypted organization key to the organization table in the SQL db. Were you able to complete that?

**Comment by bettafish15** [comment]
> In the documentation, There are few steps on how to add an encrypted organization key to the organization table in the SQL db. Were you able to complete that?

Oh i see. I didnt complete that. In the organization table i inserted a random guid generated key. I will check the documentation again and complete it. Thanks for your help and support :D
